name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Update this to your default branch if it's different (e.g., "master")

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant write access to repository contents
      pages: write

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.0" # Explicit version instead of "stable"

      # 3. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. Build the Flutter web app
      - name: Build Flutter Web
        run: flutter build web --release

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
