name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.0"

      - name: Install dependencies
        run: flutter pub get

      - name: Flutter Clean
        run: flutter clean


      - name: Build Flutter Web
        run: flutter build web

      - name: Set base href for deploy
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            sed -i 's|<base href="/">|<base href="/circle-jump/">|' build/web/index.html
          fi
      

      - name: List build/web directory
        run: ls -la build/web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
